### DISCUSSION TITLE
docker compose + portainer

### DISCUSSION THREAD

**Discussion by poudenes** [xiangechen/chili3d#70] [General]
Hi All,

I created this compose file so it can be installed using portainer
```
version: "3.9"
services:
  chili3d:
    build:
      context: https://github.com/xiangechen/chili3d.git
    logging:
      driver: none
    container_name: chili3d
    hostname: chili3d
    restart: always
    ports:
      - 8280:80
    environment:
      TZ: Europe/Amsterdam
      PUID: 1026
      PGID: 100
```
